spring.application.name=backend
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MiniSocialDB;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;
spring.datasource.username=pht
spring.datasource.password=1412
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

app.upload.dir=uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

spring.jpa.database=sql_server 
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Cấu hình JWT Secret
jwt.secret=RkdRUTNFSFBQdUpHVTJWNFRFU1RLRVlmb3IyNTZiaXRzSg==
# 24 giờ (miliseconds)
jwt.expiration=86400000 
# 7 ngày
jwt.refresh.expiration=604800000
# Cấu hình CORS (Cho phép React frontend gọi API)
cors.allowed.origins=http://localhost:5173,http://127.0.0.1:5173

spring.servlet.multipart.max-request-size=100MB

# Ép Spring Boot sử dụng bảng mã UTF-8 cho mọi Request/Response
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

